<!DOCTYPE html>
<html lang="pt-br">
<head>
	<!-- Codificação caracteres da página -->
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- SEO Geral -->
  <title>{% block title %}{% endblock %}</title>
  <meta name="description" content="Descrição de até 150 caracteres, mostrada na busca.">
  <link rel="canonical" href="Link único da página">
  <meta name="author" content="Nome do autor do site">
  <meta name="robots" content="index">

  <!-- Google+ / Schema.org -->
  <meta itemprop="name" content="Título da página">
  <meta itemprop="description" content="Descrição da página em menos de 200 caracteres.">
  <meta itemprop="image" content="https://exemplo.com/imagem.png">
  <link href="https://plus.google.com/+SuaPagina" rel="publisher">
  
  <!-- Open Graph Facebook -->
  <meta property="og:title" content="Título da página">
  <meta property="og:description" content="Descrição da página em menos de 200 caracteres."/>
  <meta property="og:url" content="Link da página">
  <meta property="og:site_name" content="Nome do site"/>
  <meta property="og:type" content="website">
  <meta property="og:image" content="https://exemplo.com/imagem.png">

  <!-- Twitter -->
  <meta name="twitter:title" content="Título da página">
  <meta name="twitter:description" content="Descrição da página em menos de 200 caracteres.">
  <meta name="twitter:url" content="Link da página">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:image" content="https://exemplo.com/imagem.png">
  <!-- <meta name="twitter:creator" content="@estevanmaito"> -->
  <meta name="twitter:site" content="@empresa">

	<!-- Configurações do estilo da página. -->
  <!-- Bootstrap core CSS -->
	<link href="{{ canonical }}/assets/css/style.css" rel="stylesheet">
  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
</head>
<body class="d-flex flex-column h-100">
    {% block body %}
    {% endblock %}

    <!--  Scripts-->                                                                               
	<!-- Custom scripts for this template -->
	<script src="{{ canonical }}assets/js/app.js"></script>
</body>
</html>